### ISSUE TITLE
New Admin Password has no limitations

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#14]
**Summary**
When editing the admin password, the admin can type without any limitations. The admin can input any length of the password and the system will accept it.

**Steps to Produce:**
Click on the Account tab:

1. Click on the Current password and type ptm_120
2. Click on the New password and type a
2. Click on the Retype New password and type a
3. Click on the submit button

**Expected Results:**
There should see an input validation stating that the password is too short.

**Actual Results:**
It accepted the new password.

![image_2022-12-14_031719814](https://user-images.githubusercontent.com/84001488/207424883-5276de85-7cd7-4a79-95ea-6a053e95aba9.png)

See 28-AdminSettings Sheet, Iteration 1-8

**Comment by andres-dalisay** [comment]
fixed with 03ced2c52a4874924f3a026ad642e4aa0bf641f9
