### ISSUE TITLE
Leaving the amount field empty is accepted

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#18]
**Summary**
Removing the amount specified of a record to a null value had no input validation. It even changed the value in the database.

**Steps to Reproduce:**
1. Go to Sales Tab:
2. Hover over on the sales record: "6:00 PM with amount ₱2283.00"
3. Click on that record
4. Edit Amount to a blank space
5. Click Save Changes
6. Go to Expense Tab:
7. Hover over on the sales record: "6:00 PM with amount ₱2283.00"
8. Click on that record
9. Edit Amount to a blank space
10. Click Save Changes

**Expected Results:**
There should be an input validation asking for input for the amount field

**Actual Results:**
There was no input validation and it changed the amount in the database to a null value

![image_2022-12-13_211928859](https://user-images.githubusercontent.com/84001488/207328624-3c23a465-eb5e-4e5c-8dc8-4aab7f85a882.png)
![image](https://user-images.githubusercontent.com/84001488/207328643-dbf29da8-1608-4cb2-afab-4346d0a9988e.png)

See 05-CSHEditSales Sheet, Iteration 1-3 for more details
Also see 08-CSHEditExpense Sheet, Iteration 1-3 for more details

**Comment by andres-dalisay** [comment]
fixed with 1eba6d6b79c404c853e44bd01d8e882f55435da4
