### ISSUE TITLE
Branch name passed from frontend is assigned as branchID; branchID is not automatically assigned

### ISSUE THREAD

**Issue by andres-dalisay** [jerichosy/CSSWENG-Team-3#2]
![image](https://user-images.githubusercontent.com/21106151/205481767-c035e827-3b16-4406-be77-ea9b083aefa0.png)
![image](https://user-images.githubusercontent.com/21106151/205481768-b2094536-2cf1-4061-8728-7c9b775e2ab8.png)

**Comment by jerichosy** [comment]
Already implemented in https://github.com/jerichosy/CSSWENG-Team-3/commit/44d9d82f3b01294df96a04bc25fa669fd24a4b61. However, it raises issue #3.
