### ISSUE TITLE
No input validation on time input

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#23]
**Summary**
There is no input validation when the inputted time is already existing in the database.

**Steps to Produce:**
1. Go to Sales tab
2. Click on Add
3. Set the time to 7:00 AM
4. Set the amount to  ₱2283.00
5. Set Customer count to 42
6. Click Add
7. Create another one using the same inputs"

**Expected Results:**
There should be an input validation saying that the inputted time is already existing in the database

**Actual Results:**
There was no input validation stating the inputted time is already used. Furthermore, it was added to the sales database

![image_2022-12-14_031327556](https://user-images.githubusercontent.com/84001488/207424228-f1064476-c8a9-4557-a754-e29aa1c26d67.png)

See 04-CSHAddSales, Iteration 1-5 for more details

**Comment by andres-dalisay** [comment]
fixed with 6c9cf265b0d949a934b8d437b955fd8874aff1da
