### ISSUE TITLE
Notes should be optional

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#24]
**Summary**
Inputs for Notes should be optional, not required when creating a new expense record

**Steps to Produce:**
1. Go to Expense tab
2. Click on Add
3. Set the Category to Grocery
4. Set the Item Name to Flour
5. Set the Amount to ₱1500.00
6. Click Add

**Expected Results:**
It should have created the new expense record and generated in the expense database

**Actual Results:**
There was an input validation stating to input in the Notes field.

![image_2022-12-14_032151027](https://user-images.githubusercontent.com/84001488/207425583-a89e37f8-1d1d-42bd-abcc-ee478657ad44.png)

See 07-CSHAddExpense, Iteration 1-4 for more details

**Comment by andres-dalisay** [comment]
fixed with 49435498f8030428b096b3edd74a52788028d668

**Comment by andres-dalisay** [comment]
fixed with 07ed533de3576d3e8ab85025bd2dcbb6c27bf41b
