### ISSUE TITLE
deleteBranch causes old/existing branchIDs to be free/available for reuse which could cause problems

### ISSUE THREAD

**Issue by jerichosy** [jerichosy/CSSWENG-Team-3#3]
Problems with static information in old db records and conflicts with CRUD operation that use branchIDs (though we have since switched to using ObjectIds).

**Solution idea:** Add isDeleted boolean field to userSchema.js. By default, this should be "false". 

**Impact on other CRUDs:** Assessed.
- login: [Add check in login to prevent login of isDeleted=true branches](https://github.com/jerichosy/CSSWENG-Team-3/commit/336781ea9066e1c0f16258dccb5cae6a70246641). This returns an error message that the account has already been deleted.
- editAdminPassword: *unaffected (Because, admin should not be modifiable by CRUDs meant for branches. Meaning the admin account should never have isDeleted=true )*
- createBranch: This isDeleted will not be set and left to the default setting. No change.
- viewBranch: [Update viewBranch to return only isDeleted=false branches](https://github.com/jerichosy/CSSWENG-Team-3/commit/8a11154f4089233990a66f63198112e59366793d)
- editBranchName: [Hide isDeleted=true from result of db query in editBranch](https://github.com/jerichosy/CSSWENG-Team-3/commit/6b478bfe3bbd7a25d8a5de52af9c9062a80de143)
- editBranchPassword: [Hide isDeleted=true from result of db query in editBranch](https://github.com/jerichosy/CSSWENG-Team-3/commit/6b478bfe3bbd7a25d8a5de52af9c9062a80de143)
- **deleteBranch**: [Change deleteBranch to do soft-delete](https://github.com/jerichosy/CSSWENG-Team-3/commit/f8ede35766074694d4cf0916273f9e8b391e72c3). [Add check in deleteBranch if branch has already been deleted](https://github.com/jerichosy/CSSWENG-Team-3/commit/d9798c6505c5ae8b17d7b8b4cd911da5924390e4). (But does not check if admin, leading to #4).

Note: Some methods like login and deleteBranch are aware of the deleted accounts. Other methods instead perform a db query with isDeleted=false filter applied.

~~Also, update and add more records in seed script.~~

**Comment by TimPin28** [comment]
Yup will do!

**Comment by jerichosy** [comment]
Wait lng reopened cause di ko pa na-update backend

**Comment by jerichosy** [comment]
@TimPin28 I'll change the attribute to isDeleted pala. I made the changes na in the GSheets.

**Comment by jerichosy** [comment]
Pull request #5 merged.
