### ISSUE TITLE
Editing the branch name is not reflecting to the branch's records (sales, expense, cheque) page

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#7]
As the scrum master said, when editing a branch name it should reflect on the records of the branch. So as of right now, the edits are only reflected on the database of the user and the view branches page.

See 15-EditBranch Sheet, Iteration 2-1

**Comment by jerichosy** [comment]
Yep, I raised this issue with Bryce recently. I'll be the one addressing this issue though. There are two ways of implementing this, and I'm still finalizing the best way to do it.
