### ISSUE TITLE
Filtering (sales, expense, cheque) by branch relies on viewBranch's result which does not include soft deleted branches, preventing deleted branches from showing in the filter by branch options

### ISSUE THREAD

**Issue by TimPin28** [jerichosy/CSSWENG-Team-3#8]
Since we should still be able to see the records of a deleted branch, we should still be able to filter it using the deleted branch. However, after deleting a branch, that branch name is gone in the filtering options of branch. It affects sales, expense, and cheques.

![image_2022-12-08_195733026](https://user-images.githubusercontent.com/84001488/206440934-7c8d17a1-f2f4-4c6b-8d18-5edb4c6c79f7.png)
Panay Avenue Paligsahan QC is not part of the filter options anymore

**Comment by jerichosy** [comment]
Just noting down my discussion with PO/SM that the current implementation of admin view sales, expense, and cheques showing documents from deleted branches by default is the desired behavior.

**Comment by jerichosy** [comment]
Just noting down my discussion with PO/SM that the current implementation of admin view sales, expense, and cheques showing documents from deleted branches by default is the desired behavior. Will discuss with @andres-dalisay as to the filtering issue.

**Comment by jerichosy** [comment]
@TimPin28 Please confirm if fixed and close if so.

**Comment by jerichosy** [comment]
Also, I'd like to add that Cymon suggested a design where the filter by branch option also denotes which have been deleted. This will require some work from the front-end and is currently not a priority as Andres expressed doubts it can be done before deadline. But I have opened #9 for it.
